name: "Build on Comment"

on:
  issue_comment:
    types: [created]

env:
  BUILD_CONFIG: Debug

jobs:
  build:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@actions /build') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      - name: Test
        run: dotnet test --no-build -c ${{ env.BUILD_CONFIG }} --logger GitHubActions --logger console;verbosity=normal
      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
