name: dotnet-build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  issue_comment:
    types: [created]

env:
  BUILD_CONFIG: Debug

jobs:
  build-dotnet:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@actions /build')) }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        if: ${{ github.event_name == 'issue_comment' }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'issue_comment' && steps.comment-branch.outputs.head_ref || ''}}
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      - name: Test
        run: dotnet test --no-build -c ${{ env.BUILD_CONFIG }} --logger GitHubActions --logger "console;verbosity=normal"
