name: dotnet-build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Debug

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      - name: Test
        run: dotnet test --no-build -c ${{ env.BUILD_CONFIG }} --logger GitHubActions --logger console;verbosity=normal
