name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # only tag

env:
  BUILD_CONFIG: Release

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      # build
      - run: dotnet build -c ${{ env.BUILD_CONFIG }} -p:Version=${{ github.event.ref }}
      # pack
      - run: dotnet pack -c ${{ env.BUILD_CONFIG }} -p:Version=${{ github.event.ref }} -o ./pack
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: nuget
          path: ./pack/

  create-release:
    needs: [build-dotnet]
    runs-on: ubuntu-latest
    steps:
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" | tee -a "$GITHUB_ENV"
      # Create Release
      - uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.ref }}
          release_name: ${{ github.event.ref }}
          draft: true
          prerelease: false
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      # upload nuget
      - run: dotnet nuget push "./nuget/*.nupkg" --skip-duplicate -s https://www.nuget.org/api/v2/package -k ${{ secrets.SYNCED_NUGET_KEY }}
