name: dotnet-build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  issue_comment:
    types: [created]

env:
  BUILD_CONFIG: Debug

jobs:
  build-dotnet:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@actions /build')) }}
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@e8b8daa837e8ea7331c0003c9c316a64c6d8b0b1 # v3.0.0
        id: comment-branch
        if: ${{ github.event_name == 'issue_comment' }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event_name == 'issue_comment' && steps.comment-branch.outputs.head_ref || ''}}
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - name: Build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      - name: Test
        run: dotnet test --no-build -c ${{ env.BUILD_CONFIG }} --logger GitHubActions --logger "console;verbosity=normal"
